In [29]:
df_gs_1 = pd.read_excel('./data/innovation/gs/동별매출지수.xlsx')
df_gs_2 = pd.read_excel('./data/innovation/gs/카테고리별매출비중.xlsx')
df_gs_3 = pd.read_excel('./data/innovation/gs/종합테이블.xlsx')

In [30]:
df_gs_1.head()

,ADMD_NM,20180401,20180402,20180403,20180404,20180405,20180406,20180407,20180408,20180409,20180410,20180411,20180412,20180413,20180414,20180415,20180416,20180417,20180418,20180419,20180420,20180421,20180422,20180423,20180424,...,20190307,20190308,20190309,20190310,20190311,20190312,20190313,20190314,20190315,20190316,20190317,20190318,20190319,20190320,20190321,20190322,20190323,20190324,20190325,20190326,20190327,20190328,20190329,20190330,20190331
0,서울특별시,1.011766,1.094877,1.096897,1.089331,1.039238,1.097272,1.053457,1.090531,1.048779,1.135352,1.105845,1.120626,1.174582,1.075983,1.038796,1.071732,1.115169,1.117529,1.143765,1.212982,1.233407,1.115071,1.022090,1.103329,...,1.055632,1.082634,1.102757,1.031219,1.031376,1.085926,1.207895,1.595711,1.201211,1.040723,0.974964,1.008744,1.057766,1.187503,1.046254,1.075611,1.089767,0.999401,1.033118,1.066640,1.067192,1.088420,1.117573,1.062068,0.932746
1,가회동,0.741018,0.855520,0.981773,1.059795,0.855990,0.924312,0.870220,1.106594,0.850314,0.862563,0.960384,1.014061,1.016913,0.861046,0.846810,1.052390,0.932183,0.838669,0.929601,1.047535,1.269160,0.874599,0.685922,0.769455,...,0.948366,1.032149,1.196526,1.082675,0.890026,0.981277,1.220457,1.374948,1.233856,1.026658,1.014909,0.992295,1.033602,1.380849,0.971669,1.069072,1.373441,0.987582,0.979205,1.046995,1.273272,1.058130,1.196671,1.251309,1.036942
2,공릉1동,0.672094,0.730841,0.703336,0.735507,0.730212,0.733291,0.725905,0.749556,0.718500,0.752295,0.735669,0.745584,0.729650,0.707655,0.713858,0.714220,0.724399,0.739032,0.743100,0.739249,0.753955,0.751809,0.752086,0.729709,...,0.737587,0.738656,0.737308,0.738198,0.748966,0.820773,0.863837,1.220267,0.864641,0.726222,0.689466,0.694539,0.747955,0.807561,0.699582,0.748217,0.776006,0.660183,0.720459,0.731680,0.711247,0.758420,0.722903,0.733375,0.630326
3,공릉2동,0.854371,0.757671,0.798944,0.814557,0.784376,0.799479,0.856979,0.921864,0.776545,0.845760,0.829452,0.819952,0.890924,0.899502,0.916850,0.797417,0.832268,0.868746,0.868730,0.961617,1.014822,1.005753,0.847708,0.924312,...,0.750125,0.789549,0.837979,0.842418,0.730906,0.802515,0.892574,1.076398,0.828022,0.764129,0.775181,0.702573,0.727662,0.831408,0.743833,0.784544,0.813513,0.861215,0.703035,0.724664,0.726578,0.754820,0.788876,0.764800,0.760009
4,교남동,0.880493,0.779827,0.828379,0.729783,0.731970,0.675765,0.891382,0.918072,0.638703,0.779614,0.727988,0.889379,0.947142,0.758437,0.924953,0.877473,0.827986,0.853469,0.764035,0.798826,0.955160,0.866869,0.682000,0.843605,...,0.786742,0.915655,1.121686,1.022142,0.852106,0.776320,0.808981,1.275592,1.017109,0.975724,1.010210,0.939339,0.853371,0.972580,0.850902,1.028600,1.198170,1.024552,0.798985,0.878509,0.849083,1.004118,0.894920,1.038392,0.963536

In [31]:
df_gs_2.head()

,ADMD_NM,ANTC_ITEM_LCLS_CD,ANTC_ITEM_LCLS_NM,20180401,20180402,20180403,20180404,20180405,20180406,20180407,20180408,20180409,20180410,20180411,20180412,20180413,20180414,20180415,20180416,20180417,20180418,20180419,20180420,20180421,20180422,...,20190307,20190308,20190309,20190310,20190311,20190312,20190313,20190314,20190315,20190316,20190317,20190318,20190319,20190320,20190321,20190322,20190323,20190324,20190325,20190326,20190327,20190328,20190329,20190330,20190331
0,가회동,10,식사,0.238186,0.248125,0.261384,0.230096,0.261243,0.247716,0.214140,0.161704,0.304228,0.268519,0.300349,0.266289,0.238324,0.224886,0.227814,0.180909,0.293603,0.265575,0.266139,0.229870,0.132045,0.169764,...,0.305448,0.286259,0.220796,0.272989,0.337804,0.307396,0.305011,0.229935,0.277421,0.306439,0.280675,0.317825,0.306006,0.256392,0.348065,0.306698,0.245688,0.289880,0.300438,0.328931,0.299950,0.324462,0.289747,0.248489,0.326596
1,가회동,20,간식,0.210444,0.214794,0.204568,0.211954,0.136507,0.177715,0.237351,0.133996,0.160922,0.178937,0.205747,0.167517,0.195885,0.165585,0.187841,0.145331,0.189515,0.190495,0.158059,0.175733,0.196627,0.159578,...,0.237524,0.217629,0.262893,0.221598,0.173627,0.208694,0.275608,0.438513,0.195772,0.219506,0.208081,0.192646,0.210778,0.184589,0.180826,0.209100,0.196512,0.247329,0.243400,0.217975,0.253515,0.202995,0.209292,0.187877,0.205701
2,가회동,30,마실거리,0.412769,0.409670,0.347117,0.316462,0.275644,0.317388,0.356301,0.192663,0.359484,0.404526,0.378195,0.384366,0.390885,0.284294,0.373539,0.277356,0.359569,0.392812,0.383814,0.403054,0.454806,0.247924,...,0.373301,0.342912,0.370428,0.389607,0.337608,0.312044,0.342781,0.263721,0.255607,0.330117,0.353467,0.389632,0.386993,0.249749,0.332135,0.353008,0.240198,0.337292,0.359860,0.361798,0.338741,0.359650,0.398432,0.286222,0.316414
3,가회동,40,홈&리빙,0.016912,0.025352,0.068550,0.043199,0.032804,0.078555,0.060966,0.017066,0.042742,0.023380,-0.000623,0.049836,0.020867,0.050441,0.041665,0.299235,0.007481,0.017992,0.022190,0.038612,0.062112,0.013582,...,0.009720,0.057335,0.032543,0.013857,0.019642,0.012409,0.019098,0.005176,0.026847,0.029610,0.052020,0.017236,0.020333,0.006602,0.031765,0.033069,0.032446,0.019224,0.016066,0.031477,0.013807,0.011708,0.016272,0.030741,0.032521
4,가회동,50,헬스&뷰티,0.090471,0.086298,0.098328,0.096238,0.223634,0.130952,0.100137,0.407685,0.081960,0.074466,0.089784,0.051454,0.072898,0.226836,0.121656,0.064384,0.086151,0.056458,0.083095,0.101332,0.101435,0.355045,...,0.060067,0.066408,0.073897,0.062732,0.099660,0.106482,0.042010,0.043440,0.220375,0.083952,0.061492,0.068091,0.053834,0.268099,0.059216,0.056393,0.219799,0.088639,0.043856,0.040440,0.054808,0.062644,0.057353,0.201487,0.079969

In [32]:
df_gs_3.head()

,OPER_DT,BOR_CD,ADMD_CD,AMT_IND,LCLS_10_P,LCLS_20_P,LCLS_30_P,LCLS_40_P,LCLS_50_P,LCLS_60_P,LCLS_70_P,LCLS_80_P
0,20180401,1111,11110515,0.736933,0.279018,0.299569,0.334816,0.015636,0.053782,0.000265,0.013092,0.003823
1,20180401,1111,11110530,1.258473,0.237403,0.257984,0.349826,0.045502,0.092581,0.004988,0.002467,0.009250
2,20180401,1111,11110540,0.674164,0.254081,0.246844,0.324434,0.065025,0.089691,NaN,0.013212,0.006712
3,20180401,1111,11110550,1.010874,0.416368,0.217715,0.282613,0.026738,0.036622,0.005893,0.012295,0.001756
4,20180401,1111,11110560,1.012942,0.311321,0.267387,0.262358,0.014736,0.135350,NaN,0.007270,0.001577

In [33]:
len(df_gs_3.OPER_DT.unique()), len(df_gs_3.ADMD_CD.unique())

(365, 36)

In [34]:
df_gs_3.isnull().sum()

OPER_DT         0
BOR_CD          0
ADMD_CD         0
AMT_IND        15
LCLS_10_P      15
LCLS_20_P      15
LCLS_30_P      15
LCLS_40_P      47
LCLS_50_P      17
LCLS_60_P    1065
LCLS_70_P     254
LCLS_80_P     597
dtype: int64

In [35]:
np.where(df_gs_3.groupby('ADMD_CD').count()['OPER_DT'] != 365)[0]

array([], dtype=int64)

In [36]:
df_gs_3.groupby('ADMD_CD').count()['OPER_DT'].iloc[[13, 33]]

ADMD_CD
11110680    365
11350700    365
Name: OPER_DT, dtype: int64

##### df_gs_3 결측 15개 채워넣음

In [37]:
df_gs_3.shape

(13140, 12)

In [38]:
df_shinhan = pd.read_csv('./data/innovation/shinhan/CARD_SPENDING/CARD_SPENDING.txt', sep='	')

In [39]:
df_shinhan.head()

     STD_DD  GU_CD  DONG_CD  MCT_CAT_CD SEX_CD  AGE_CD  USE_CNT  USE_AMT
0  20180401    110      515          21      F      55        4       22
1  20180401    110      515          21      M      20       35      184
2  20180401    110      515          21      M      25       70      425
3  20180401    110      515          21      M      30       18       82
4  20180401    110      515          21      M      35        4       44

In [40]:
df_shinhan.shape

(1998575, 8)

In [41]:
df_sns = pd.read_excel('./data/innovation/sns/SNS_1.xlsx')

In [42]:
df_sns.head()

,DOCID,SECTION,DATE,TITLE,CONTENT
0,204172453,블로그,20181102235900,신동탄 이안파밀리에 눈에 보이는 프리미엄 진짜네요,분 양 정 보 신동탄 이안파밀리에 눈에 보이는 프리미엄 진짜네요 유쾌한 분양킴 2...
1,204172474,블로그,20181102235700,느린 점심點心,생활 속의 단상 느린 점심點心 묘광거사 2018 11 2 2357 URL 복사 이...
2,204172506,블로그,20181102235400,한화 태양의 숲 조성으로 미세먼지도 막고 환경도 지켜요,한화프렌즈 한화 태양의 숲 조성으로 미세먼지도 막고 환경도 지켜요 아르엘 2018...
3,204172546,블로그,20181102235400,섬유유연제추천 미세먼지까지 잡아 주는 착한 샤프란 섬유유연제 quot; 꽃담초 quot;,쇼핑 섬유유연제추천 미세먼지까지 잡아 주는 착한 샤프란 섬유유연제 꽃담초 요미요...
4,204172587,블로그,20181102235200,핑거루트 허브 다이어트 남자 몸매관리 후기,리뷰 핑거루트 허브 다이어트 남자 몸매관리 후기 김종성유통 2018 11 2 23...

In [43]:
df_sns.shape, df_shinhan.shape, df_asos_1.shape, df_gs_3.shape

((176873, 5), (1998575, 8), (525600, 11), (13140, 12))

# Merge Data

##### GS retail 처리

In [44]:
df_gs_3.head()

,OPER_DT,BOR_CD,ADMD_CD,AMT_IND,LCLS_10_P,LCLS_20_P,LCLS_30_P,LCLS_40_P,LCLS_50_P,LCLS_60_P,LCLS_70_P,LCLS_80_P
0,20180401,1111,11110515,0.736933,0.279018,0.299569,0.334816,0.015636,0.053782,0.000265,0.013092,0.003823
1,20180401,1111,11110530,1.258473,0.237403,0.257984,0.349826,0.045502,0.092581,0.004988,0.002467,0.009250
2,20180401,1111,11110540,0.674164,0.254081,0.246844,0.324434,0.065025,0.089691,NaN,0.013212,0.006712
3,20180401,1111,11110550,1.010874,0.416368,0.217715,0.282613,0.026738,0.036622,0.005893,0.012295,0.001756
4,20180401,1111,11110560,1.012942,0.311321,0.267387,0.262358,0.014736,0.135350,NaN,0.007270,0.001577

* Add GU_NM, DONG_NM

In [45]:
ADMD_temp1 = list(df_gs_3.ADMD_CD.unique())

In [46]:
ADMD_temp2 = ["청운효자동","사직동", "삼청동", "부암동", "평창동", "무악동",
              "교남동", "가회동", "종로1.2.3.4가동", "종로5.6가동", "이화동",
              "혜화동", "창신1동", "창신2동", "창신3동", "숭인1동", "숭인2동",
              "월계1동", "월계2동", "월계3동", "공릉1동", "공릉2동", "하계1동",
              "하계2동", "중계본동", "중계1동", "중계4동", "중계2.3동", "상계1동",
              "상계2동", "상계3.4동", "상계5동", "상계6.7동", "상계8동", "상계9동", "상계10동"]

In [47]:
len(ADMD_temp1), len(ADMD_temp2)

(36, 36)

In [48]:
BOR_NM_dict = {1111:'종로구', 1135:'노원구'}
ADMD_NM_dict = dict()
for i in range(len(ADMD_temp1)):
    ADMD_NM_dict[ADMD_temp1[i]]=ADMD_temp2[i]

In [49]:
gs_cols_name_dict = {'OPER_DT':'DATE', 'BOR_CD':'GU_CD', 'ADMD_CD':'DONG_CD'}
df_gs_total = df_gs_3.rename(columns=gs_cols_name_dict)

In [50]:
GU_NM_list = [BOR_NM_dict[i] for i in df_gs_total.GU_CD]

df_gs_total['GU_NM']=GU_NM_list

In [51]:
DONG_NM_list = [ADMD_NM_dict[i] for i in df_gs_total.DONG_CD]
df_gs_total['DONG_NM'] = DONG_NM_list

* change entry from ratio to price

In [52]:
df_gs_total.AMT_IND = df_gs_total.AMT_IND*1024712

In [53]:
change_cols = ['LCLS_10_P', 'LCLS_20_P', 'LCLS_30_P', 'LCLS_40_P', 'LCLS_50_P', 'LCLS_60_P', 'LCLS_70_P', 'LCLS_80_P']
for i in change_cols:
    df_gs_total[i] = df_gs_total[i]*df_gs_total.AMT_IND

In [54]:
df_gs_total.head()

,DATE,GU_CD,DONG_CD,AMT_IND,LCLS_10_P,LCLS_20_P,LCLS_30_P,LCLS_40_P,LCLS_50_P,LCLS_60_P,LCLS_70_P,LCLS_80_P,GU_NM,DONG_NM
0,20180401,1111,11110515,755144.0,210698.680246,226217.675108,252833.916296,11807.246091,40613.486554,199.999934,9886.246727,2886.749044,종로구,청운효자동
1,20180401,1111,11110530,1289572.0,306148.368702,332688.878992,451125.424913,58678.022751,119389.796290,6431.752494,3181.751234,11928.004625,종로구,사직동
2,20180401,1111,11110540,690824.0,175525.000000,170526.000000,224127.000000,44921.000000,61961.000000,NaN,9127.000000,4637.000000,종로구,삼청동
3,20180401,1111,11110550,1035855.0,431297.145908,225521.195571,292746.429347,27696.243316,37934.740845,6104.498527,12735.996926,1818.749561,종로구,부암동
4,20180401,1111,11110560,1037974.0,323143.000000,277541.000000,272321.000000,15296.000000,140490.000000,NaN,7546.000000,1637.000000,종로구,평창동

##### ShinHan Card 처리

In [55]:
df_shinhan.head()

     STD_DD  GU_CD  DONG_CD  MCT_CAT_CD SEX_CD  AGE_CD  USE_CNT  USE_AMT
0  20180401    110      515          21      F      55        4       22
1  20180401    110      515          21      M      20       35      184
2  20180401    110      515          21      M      25       70      425
3  20180401    110      515          21      M      30       18       82
4  20180401    110      515          21      M      35        4       44

In [56]:
SH_rename_cols_dict = {'STD_DD':'DATE'}
df_shinhan.rename(columns=SH_rename_cols_dict, inplace=True)

* Add GU_NM, DONG_NM

In [57]:
SH_DONG_NM_list = [str(df_shinhan.GU_CD[i])+str(df_shinhan.DONG_CD[i]) for i in range(len(df_shinhan))]

In [58]:
df_shinhan.DONG_CD = SH_DONG_NM_list

In [59]:
DONG_temp1 = list(df_shinhan.DONG_CD.unique())

In [60]:
DONG_temp2 = ["청운효자동","사직동", "삼청동", "부암동", "평창동", "무악동",
              "교남동", "가회동", "종로1.2.3.4가동", "종로5.6가동", "이화동",
              "혜화동", "창신1동", "창신2동", "창신3동", "숭인1동", "숭인2동",
              "월계1동", "월계2동", "월계3동", "공릉1동", "공릉2동", "하계1동",
              "하계2동", "중계본동", "중계1동", "중계4동", "중계2.3동", "상계1동",
              "상계2동", "상계3.4동", "상계5동", "상계6.7동", "상계8동", "상계9동", "상계10동"]

In [61]:
len(DONG_temp1), len(DONG_temp2)

(36, 36)

In [62]:
SH_GU_NM_dict = {110:'종로구', 350:'노원구'}
SH_DONG_NM_dict = dict()
for i in range(len(DONG_temp1)):
    SH_DONG_NM_dict[DONG_temp1[i]]=DONG_temp2[i]

In [63]:
SH_GU_NM_list = [SH_GU_NM_dict[i] for i in df_shinhan.GU_CD]

df_shinhan['GU_NM']=SH_GU_NM_list

In [64]:
SH_DONG_NM_list = [SH_DONG_NM_dict[i] for i in df_shinhan.DONG_CD]
df_shinhan['DONG_NM'] = SH_DONG_NM_list

* MCT_CAT_CD to column

In [65]:
df_shinhan.head()

,DATE,GU_CD,DONG_CD,MCT_CAT_CD,SEX_CD,AGE_CD,USE_CNT,USE_AMT,GU_NM,DONG_NM
0,20180401,110,110515,21,F,55,4,22,종로구,청운효자동
1,20180401,110,110515,21,M,20,35,184,종로구,청운효자동
2,20180401,110,110515,21,M,25,70,425,종로구,청운효자동
3,20180401,110,110515,21,M,30,18,82,종로구,청운효자동
4,20180401,110,110515,21,M,35,4,44,종로구,청운효자동

In [120]:
df_group = df_shinhan.groupby(['DATE', 'DONG_NM', 'MCT_CAT_CD'
#                                ,'SEX_CD', 'AGE_CD'
                              ]).sum()

In [121]:
df_group = df_group.USE_AMT

In [122]:
df_group =pd.DataFrame(df_group)

In [123]:
df_group.head()

                             USE_AMT
DATE     DONG_NM MCT_CAT_CD
20180401 가회동     22              110
                 34              530
                 35              808
                 40            17527
                 42             9712

In [124]:
df_group = df_group.unstack()

In [125]:
cols_name_list = ['레저_USE_AMT', '문화취미_USE_AMT', '가구_USE_AMT', '전기_USE_AMT',
                  '주방_USE_AMT', '연료_USE_AMT', '광학_USE_AMT', '가전_USE_AMT', '유통업_USE_AMT',
                  '의복_USE_AMT', '직물_USE_AMT', '신변잡화_USE_AMT','서적문구_USE_AMT', '사무통신_USE_AMT',
                  '자동차판매_USE_AMT', '자동차정비_USE_AMT', '의료기관_USE_AMT', '보건위생_USE_AMT', '요식업소_USE_AMT',
                  '음료식품_USE_AMT', '수리서비스_USE_AMT']

In [126]:
df_group.columns = cols_name_list

In [128]:
df_group.head()

                  레저_USE_AMT  문화취미_USE_AMT  가구_USE_AMT  전기_USE_AMT  \
DATE     DONG_NM
20180401 가회동             NaN         110.0         NaN         NaN
         공릉1동         2642.0        1100.0         NaN         NaN
         공릉2동         3715.0        1117.0         NaN         NaN
         교남동             NaN           NaN         NaN         NaN
         무악동           412.0           NaN         NaN         NaN

                  주방_USE_AMT  연료_USE_AMT  광학_USE_AMT  가전_USE_AMT  유통업_USE_AMT  \
DATE     DONG_NM
20180401 가회동             NaN         NaN       530.0       808.0      17527.0
         공릉1동          175.0     68273.0       289.0     38598.0     102056.0
         공릉2동            NaN    108708.0      1533.0         NaN      89712.0
         교남동             NaN         NaN         NaN         NaN      12461.0
         무악동             NaN         NaN         NaN         NaN      10589.0

                  의복_USE_AMT  직물_USE_AMT  신변잡화_USE_AMT  서적문구_USE_AMT  \
DATE     DONG_NM
20180401 가회동          9712.0         NaN       11661.0         581.0
         공릉1동         4354.0       176.0         264.0         437.0
         공릉2동          367.0         NaN          55.0        1592.0
         교남동          3863.0         NaN           NaN          88.0
         무악동             NaN         NaN           NaN           NaN

                  사무통신_USE_AMT  자동차판매_USE_AMT  자동차정비_USE_AMT  의료기관_USE_AMT  \
DATE     DONG_NM
20180401 가회동               NaN            NaN            NaN           NaN
         공릉1동            101.0            NaN          789.0       16492.0
         공릉2동            101.0            NaN          346.0        7372.0
         교남동               NaN            NaN          348.0       96272.0
         무악동               NaN            NaN          101.0       25985.0

                  보건위생_USE_AMT  요식업소_USE_AMT  음료식품_USE_AMT  수리서비스_USE_AMT
DATE     DONG_NM
20180401 가회동             592.0       58298.0        2028.0            NaN
         공릉1동          17485.0      206044.0       15646.0          128.0
         공릉2동          19001.0      107804.0       14667.0            NaN
         교남동            2687.0       21714.0        2118.0          286.0
         무악동             376.0       11702.0        2215.0            NaN

In [132]:
df_shinhan_total = df_group.reset_index()

* MCT_CAT_CD to column (GU)

In [203]:
df_GU_group = df_shinhan.groupby(['DATE', 'GU_NM', 'MCT_CAT_CD'
#                                ,'SEX_CD', 'AGE_CD'
                              ]).sum()

In [204]:
df_GU_group = pd.DataFrame(df_GU_group.USE_AMT)

In [205]:
df_GU_group = df_GU_group.unstack()

In [206]:
cols_name_list = ['레저_USE_AMT', '문화취미_USE_AMT', '가구_USE_AMT', '전기_USE_AMT',
                  '주방_USE_AMT', '연료_USE_AMT', '광학_USE_AMT', '가전_USE_AMT', '유통업_USE_AMT',
                  '의복_USE_AMT', '직물_USE_AMT', '신변잡화_USE_AMT','서적문구_USE_AMT', '사무통신_USE_AMT',
                  '자동차판매_USE_AMT', '자동차정비_USE_AMT', '의료기관_USE_AMT', '보건위생_USE_AMT', '요식업소_USE_AMT',
                  '음료식품_USE_AMT', '수리서비스_USE_AMT']

In [207]:
df_GU_group.columns = cols_name_list

In [208]:
df_GU_group.head()

                레저_USE_AMT  문화취미_USE_AMT  가구_USE_AMT  전기_USE_AMT  주방_USE_AMT  \
DATE     GU_NM
20180401 노원구       38739.0       40507.0     21890.0         NaN      2885.0
         종로구       18134.0       70755.0         NaN        48.0      1974.0
20180402 노원구       24158.0       24220.0      3449.0      2889.0      6052.0
         종로구       13887.0       38318.0         NaN      2356.0      7557.0
20180403 노원구       26960.0       18091.0      9782.0      3999.0     33470.0

                연료_USE_AMT  광학_USE_AMT  가전_USE_AMT  유통업_USE_AMT  의복_USE_AMT  \
DATE     GU_NM
20180401 노원구      364300.0     13812.0    145154.0    3319741.0    111198.0
         종로구       21652.0      6411.0      5655.0    1296166.0    221297.0
20180402 노원구    12114002.0      4620.0    153582.0    2132470.0     97721.0
         종로구       29862.0      5267.0     41640.0    1977942.0    253125.0
20180403 노원구      369762.0      2961.0     88636.0    2182615.0    102555.0

                직물_USE_AMT  신변잡화_USE_AMT  서적문구_USE_AMT  사무통신_USE_AMT  \
DATE     GU_NM
20180401 노원구        3804.0       29595.0      101676.0         842.0
         종로구       24618.0      204555.0      777664.0        5322.0
20180402 노원구         955.0       28998.0       92120.0       22499.0
         종로구       68581.0      248638.0      638999.0       25334.0
20180403 노원구        6267.0       20211.0       74786.0        2924.0

                자동차판매_USE_AMT  자동차정비_USE_AMT  의료기관_USE_AMT  보건위생_USE_AMT  \
DATE     GU_NM
20180401 노원구              NaN        24501.0      145702.0      281767.0
         종로구              NaN        34222.0      360798.0      140561.0
20180402 노원구           5388.0       115142.0     1272969.0      241671.0
         종로구           5396.0        67448.0     4277631.0      156384.0
20180403 노원구          18559.0        54010.0     1326599.0      220107.0

                요식업소_USE_AMT  음료식품_USE_AMT  수리서비스_USE_AMT
DATE     GU_NM
20180401 노원구       1834927.0      159470.0        10236.0
         종로구       2593107.0      108895.0         3457.0
20180402 노원구       1201052.0      182166.0        33036.0
         종로구       2523569.0      202107.0        18594.0
20180403 노원구       1312038.0      177138.0        28567.0

In [209]:
df_shinhan_total_GU = df_GU_group.reset_index()

In [218]:
df_shinhan_total_GU.head()

,DATE,GU_NM,레저_USE_AMT,문화취미_USE_AMT,가구_USE_AMT,전기_USE_AMT,주방_USE_AMT,연료_USE_AMT,광학_USE_AMT,가전_USE_AMT,유통업_USE_AMT,의복_USE_AMT,직물_USE_AMT,신변잡화_USE_AMT,서적문구_USE_AMT,사무통신_USE_AMT,자동차판매_USE_AMT,자동차정비_USE_AMT,의료기관_USE_AMT,보건위생_USE_AMT,요식업소_USE_AMT,음료식품_USE_AMT,수리서비스_USE_AMT
0,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0
1,20180401,종로구,18134.0,70755.0,NaN,48.0,1974.0,21652.0,6411.0,5655.0,1296166.0,221297.0,24618.0,204555.0,777664.0,5322.0,NaN,34222.0,360798.0,140561.0,2593107.0,108895.0,3457.0
2,20180402,노원구,24158.0,24220.0,3449.0,2889.0,6052.0,12114002.0,4620.0,153582.0,2132470.0,97721.0,955.0,28998.0,92120.0,22499.0,5388.0,115142.0,1272969.0,241671.0,1201052.0,182166.0,33036.0
3,20180402,종로구,13887.0,38318.0,NaN,2356.0,7557.0,29862.0,5267.0,41640.0,1977942.0,253125.0,68581.0,248638.0,638999.0,25334.0,5396.0,67448.0,4277631.0,156384.0,2523569.0,202107.0,18594.0
4,20180403,노원구,26960.0,18091.0,9782.0,3999.0,33470.0,369762.0,2961.0,88636.0,2182615.0,102555.0,6267.0,20211.0,74786.0,2924.0,18559.0,54010.0,1326599.0,220107.0,1312038.0,177138.0,28567.0

##### SKT인구 처리

In [68]:
df_skt_time.head()

,STD_YM,STD_YMD,HDONG_CD,HDONG_NM,TMST_00,TMST_01,TMST_02,TMST_03,TMST_04,TMST_05,TMST_06,TMST_07,TMST_08,TMST_09,TMST_10,TMST_11,TMST_12,TMST_13,TMST_14,TMST_15,TMST_16,TMST_17,TMST_18,TMST_19,TMST_20,TMST_21,TMST_22,TMST_23
0,201804,20180401,1111051500,청운효자동,609.11,447.82,301.75,217.03,237.07,318.75,519.28,1131.14,1588.58,1881.46,2520.06,2684.31,2721.33,3087.27,3097.34,2550.96,2464.35,2327.44,1933.71,1597.47,1331.83,1231.07,1041.82,624.62
1,201804,20180401,1111053000,사직동,1904.32,1319.04,951.80,779.08,779.14,1355.75,2473.61,3572.35,6145.07,7703.36,8742.41,9296.29,10060.52,10990.83,10166.17,9179.66,8899.18,8318.59,7009.69,5750.79,5137.36,4532.06,3589.93,2308.88
2,201804,20180401,1111054000,삼청동,216.30,158.05,91.13,85.30,86.76,146.87,287.34,391.87,784.74,1437.12,1652.25,1985.75,2485.91,2640.20,2361.17,2126.52,1998.35,1794.76,1281.02,1059.50,875.79,691.84,433.89,229.83
3,201804,20180401,1111055000,부암동,1300.61,904.38,670.74,433.02,571.34,771.25,1031.59,1810.52,2557.06,3311.50,4508.32,4223.61,4491.89,5372.25,5155.72,4888.78,5111.07,5067.47,4148.24,3502.62,3217.30,2925.42,2374.94,1382.12
4,201804,20180401,1111056000,평창동,2523.88,2168.69,1672.82,1300.87,1400.14,1686.09,2277.03,3703.51,4682.92,7410.61,9315.43,10435.22,10004.64,11152.68,10460.65,9539.91,8973.38,7940.15,6992.54,6460.50,5661.25,5210.50,4416.75,3060.66

In [69]:
df_skt_time.HDONG_CD.iloc[0]

1111051500

In [70]:
df_skt_time['GU_CD'] = [int(str(df_skt_time.HDONG_CD.iloc[i])[:4]) for i in range(len(df_skt_time))]

In [72]:
df_skt_time.head()

,STD_YM,STD_YMD,HDONG_CD,HDONG_NM,TMST_00,TMST_01,TMST_02,TMST_03,TMST_04,TMST_05,TMST_06,TMST_07,TMST_08,TMST_09,TMST_10,TMST_11,TMST_12,TMST_13,TMST_14,TMST_15,TMST_16,TMST_17,TMST_18,TMST_19,TMST_20,TMST_21,TMST_22,TMST_23,GU_CD
0,201804,20180401,1111051500,청운효자동,609.11,447.82,301.75,217.03,237.07,318.75,519.28,1131.14,1588.58,1881.46,2520.06,2684.31,2721.33,3087.27,3097.34,2550.96,2464.35,2327.44,1933.71,1597.47,1331.83,1231.07,1041.82,624.62,1111
1,201804,20180401,1111053000,사직동,1904.32,1319.04,951.80,779.08,779.14,1355.75,2473.61,3572.35,6145.07,7703.36,8742.41,9296.29,10060.52,10990.83,10166.17,9179.66,8899.18,8318.59,7009.69,5750.79,5137.36,4532.06,3589.93,2308.88,1111
2,201804,20180401,1111054000,삼청동,216.30,158.05,91.13,85.30,86.76,146.87,287.34,391.87,784.74,1437.12,1652.25,1985.75,2485.91,2640.20,2361.17,2126.52,1998.35,1794.76,1281.02,1059.50,875.79,691.84,433.89,229.83,1111
3,201804,20180401,1111055000,부암동,1300.61,904.38,670.74,433.02,571.34,771.25,1031.59,1810.52,2557.06,3311.50,4508.32,4223.61,4491.89,5372.25,5155.72,4888.78,5111.07,5067.47,4148.24,3502.62,3217.30,2925.42,2374.94,1382.12,1111
4,201804,20180401,1111056000,평창동,2523.88,2168.69,1672.82,1300.87,1400.14,1686.09,2277.03,3703.51,4682.92,7410.61,9315.43,10435.22,10004.64,11152.68,10460.65,9539.91,8973.38,7940.15,6992.54,6460.50,5661.25,5210.50,4416.75,3060.66,1111

In [73]:
skt_GU_NM_dict = {1111:'종로구', 1135:'노원구'}
df_skt_time['GU_NM'] = [skt_GU_NM_dict[i] for i in df_skt_time.GU_CD]

In [74]:
pop_rename_dict = {'STD_YMD':'DATE', 'HDONG_CD':'DONG_CD', 'HDONG_NM':'DONG_NM',}

In [75]:
df_skt_time.rename(columns=pop_rename_dict, inplace=True)

In [76]:
df_skt_time.head()

,STD_YM,DATE,DONG_CD,DONG_NM,TMST_00,TMST_01,TMST_02,TMST_03,TMST_04,TMST_05,TMST_06,TMST_07,TMST_08,TMST_09,TMST_10,TMST_11,TMST_12,TMST_13,TMST_14,TMST_15,TMST_16,TMST_17,TMST_18,TMST_19,TMST_20,TMST_21,TMST_22,TMST_23,GU_CD,GU_NM
0,201804,20180401,1111051500,청운효자동,609.11,447.82,301.75,217.03,237.07,318.75,519.28,1131.14,1588.58,1881.46,2520.06,2684.31,2721.33,3087.27,3097.34,2550.96,2464.35,2327.44,1933.71,1597.47,1331.83,1231.07,1041.82,624.62,1111,종로구
1,201804,20180401,1111053000,사직동,1904.32,1319.04,951.80,779.08,779.14,1355.75,2473.61,3572.35,6145.07,7703.36,8742.41,9296.29,10060.52,10990.83,10166.17,9179.66,8899.18,8318.59,7009.69,5750.79,5137.36,4532.06,3589.93,2308.88,1111,종로구
2,201804,20180401,1111054000,삼청동,216.30,158.05,91.13,85.30,86.76,146.87,287.34,391.87,784.74,1437.12,1652.25,1985.75,2485.91,2640.20,2361.17,2126.52,1998.35,1794.76,1281.02,1059.50,875.79,691.84,433.89,229.83,1111,종로구
3,201804,20180401,1111055000,부암동,1300.61,904.38,670.74,433.02,571.34,771.25,1031.59,1810.52,2557.06,3311.50,4508.32,4223.61,4491.89,5372.25,5155.72,4888.78,5111.07,5067.47,4148.24,3502.62,3217.30,2925.42,2374.94,1382.12,1111,종로구
4,201804,20180401,1111056000,평창동,2523.88,2168.69,1672.82,1300.87,1400.14,1686.09,2277.03,3703.51,4682.92,7410.61,9315.43,10435.22,10004.64,11152.68,10460.65,9539.91,8973.38,7940.15,6992.54,6460.50,5661.25,5210.50,4416.75,3060.66,1111,종로구

### Merge Card, Retail, Pop

In [133]:
skt_cols_list = ['DATE', 'DONG_NM', 'TMST_00', 'TMST_01', 'TMST_02', 'TMST_03',
                 "TMST_04", "TMST_05", "TMST_06", "TMST_07", "TMST_08", "TMST_09", "TMST_10",
                 "TMST_11", "TMST_12", "TMST_13", "TMST_14", "TMST_15", "TMST_16", "TMST_17", "TMST_18", "TMST_19",
                 "TMST_20", "TMST_21", "TMST_22", "TMST_23"]

In [136]:
df_hang_total = df_shinhan_total.merge(df_skt_time[skt_cols_list], on=['DATE', 'DONG_NM'])

In [137]:
gs_cols_list = ["DATE", "LCLS_10_P", "LCLS_20_P", "LCLS_30_P", "LCLS_40_P", "LCLS_50_P", "LCLS_60_P", 
                "LCLS_70_P", "LCLS_80_P", "DONG_NM"]

In [138]:
df_hang_total = df_hang_total.merge(df_gs_total[gs_cols_list], on=['DATE', 'DONG_NM'])

In [139]:
df_hang_total

,DATE,DONG_NM,레저_USE_AMT,문화취미_USE_AMT,가구_USE_AMT,전기_USE_AMT,주방_USE_AMT,연료_USE_AMT,광학_USE_AMT,가전_USE_AMT,유통업_USE_AMT,의복_USE_AMT,직물_USE_AMT,신변잡화_USE_AMT,서적문구_USE_AMT,사무통신_USE_AMT,자동차판매_USE_AMT,자동차정비_USE_AMT,의료기관_USE_AMT,보건위생_USE_AMT,요식업소_USE_AMT,음료식품_USE_AMT,수리서비스_USE_AMT,TMST_00,TMST_01,...,TMST_07,TMST_08,TMST_09,TMST_10,TMST_11,TMST_12,TMST_13,TMST_14,TMST_15,TMST_16,TMST_17,TMST_18,TMST_19,TMST_20,TMST_21,TMST_22,TMST_23,LCLS_10_P,LCLS_20_P,LCLS_30_P,LCLS_40_P,LCLS_50_P,LCLS_60_P,LCLS_70_P,LCLS_80_P
0,20180401,가회동,NaN,110.0,NaN,NaN,NaN,NaN,530.0,808.0,17527.0,9712.0,NaN,11661.0,581.0,NaN,NaN,NaN,NaN,592.0,58298.0,2028.0,NaN,258.39,220.10,...,320.00,640.94,866.80,1092.78,1361.76,1585.97,1494.60,1603.95,1365.79,1297.30,1097.03,863.50,677.32,642.33,601.22,544.75,269.50,180862.119093,159796.605222,313428.206385,12841.508456,68697.545236,7318.004819,15636.010296,750.000494
1,20180401,공릉1동,2642.0,1100.0,NaN,NaN,175.0,68273.0,289.0,38598.0,102056.0,4354.0,176.0,264.0,437.0,101.0,NaN,789.0,16492.0,17485.0,206044.0,15646.0,128.0,4132.87,2917.44,...,3864.96,5713.36,7013.81,8737.52,9302.84,9804.95,11344.93,11974.15,11899.08,12310.70,12736.98,11215.19,10853.89,9296.98,8484.84,6643.67,4320.01,219548.246363,142648.301782,249461.090555,22808.674946,34370.679143,6672.169089,9916.920267,3276.917856
2,20180401,공릉2동,3715.0,1117.0,NaN,NaN,NaN,108708.0,1533.0,NaN,89712.0,367.0,NaN,55.0,1592.0,101.0,NaN,346.0,7372.0,19001.0,107804.0,14667.0,NaN,3039.81,2170.86,...,4504.96,5774.51,7616.00,9632.36,9509.23,11026.08,12229.50,11702.05,11217.02,11061.01,11367.48,9439.37,8870.76,7744.34,6746.97,5644.98,3777.58,277161.373368,221406.098842,289866.067563,18284.991646,43640.080061,5318.197570,14854.493213,4952.697737
3,20180401,교남동,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12461.0,3863.0,NaN,NaN,88.0,NaN,NaN,348.0,96272.0,2687.0,21714.0,2118.0,286.0,528.17,338.88,...,663.56,1140.63,1568.57,1905.76,1679.05,1982.61,2007.89,2036.69,1961.85,2013.86,2002.11,1590.22,1367.49,1335.09,1299.15,896.60,495.97,303187.000000,235302.000000,223207.000000,69663.000000,41738.000000,9000.000000,17272.000000,2883.000000
4,20180401,무악동,412.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10589.0,NaN,NaN,NaN,NaN,NaN,NaN,101.0,25985.0,376.0,11702.0,2215.0,NaN,332.06,205.21,...,342.80,618.95,1197.67,1269.95,1006.10,1120.90,1243.10,1385.03,1311.60,1161.81,1207.60,1268.47,881.12,931.12,828.30,649.49,382.69,681754.000000,411452.000000,716385.000000,44301.000000,96792.000000,24463.000000,7636.000000,9001.000000
5,20180401,부암동,NaN,624.0,NaN,NaN,NaN,2515.0,NaN,NaN,9055.0,289.0,NaN,420.0,NaN,NaN,NaN,NaN,11491.0,504.0,60439.0,2249.0,NaN,1300.61,904.38,...,1810.52,2557.06,3311.50,4508.32,4223.61,4491.89,5372.25,5155.72,4888.78,5111.07,5067.47,4148.24,3502.62,3217.30,2925.42,2374.94,1382.12,431297.145908,225521.195571,292746.429347,27696.243316,37934.740845,6104.498527,12735.996926,1818.749561
6,20180401,사직동,75.0,9782.0,NaN,NaN,NaN,3189.0,446.0,NaN,280535.0,5070.0,NaN,2255.0,22781.0,NaN,NaN,20991.0,1171.0,16982.0,296399.0,8114.0,333.0,1904.32,1319.04,...,3572.35,6145.07,7703.36,8742.41,9296.29,10060.52,10990.83,10166.17,9179.66,8899.18,8318.59,7009.69,5750.79,5137.36,4532.06,3589.93,2308.88,306148.368702,332688.878992,451125.424913,58678.022751,119389.796290,6431.752494,3181.751234,11928.004625
7,20180401,삼청동,NaN,7373.0,NaN,NaN,NaN,NaN,2090.0,NaN,12934.0,31916.0,NaN,9337.0,430.0,NaN,NaN,1428.0,NaN,4200.0,132897.0,3418.0,NaN,216.30,158.05,...,391.87,784.74,1437.12,1652.25,1985.75,2485.91,2640.20,2361.17,2126.52,1998.35,1794.76,1281.02,1059.50,875.79,691.84,433.89,229.83,175525.000000,170526.000000,224127.000000,44921.000000,61961.000000,NaN,9127.000000,4637.000000
8,20180401,상계10동,154.0,NaN,NaN,NaN,NaN,NaN,NaN,250.0,11468.0,4062.0,NaN,319.0,8413.0,NaN,NaN,NaN,NaN,4178.0,10782.0,1792.0,NaN,801.50,586.72,...,693.96,1360.05,1852.12,2198.11,1943.54,2561.30,2764.10,2628.86,2639.44,2673.32,2501.66,2478.50,2064.46,1882.61,1590.16,1295.66,823.39,241980.000000,167638.666667,308041.666667,10149.333333,35662.000000,2272.666667,4666.666667,1516.000000
9,20180401,상계1동,6207.0,2333.0,NaN,NaN,131.0,68407.0,6439.0,38655.0,129586.0,6825.0,NaN,784.0,4862.0,88.0,NaN,228.0,6571.0,27492.0,246875.0,15701.0,1183.0,2339.24,1699.94,...,2728.90,4420.39,6444.59,8466.89,8467.84,9209.10,9498.13,9566.45,9946.06,9982.94,9091.23,8177.55,6591.49,5888.17,4784.02,3590.25,2433.04,216427.088941,193871.079671,318829.575467,21702.231141,41001.239072,7118.114036,9252.559358,2928.112314
10,20180401,상계2동,5716.0,16993.0,964.0,NaN,431.0,9465.0,2260.0,41395.0,782233.0,37400.0,NaN,13615.0,9483.0,NaN,NaN,5296.0,16159.0,54790.0,430270.0,11089.0,1257.0,1625.41,1323.89,...,1502.95,3437.25,4815.83,6055.25,4921.98,6597.56,6901.16,7148.15,6654.20,7040.70,6470.97,6326.26,5096.45,4435.29,3627.67,3145.05,2008.57,444054.159469,377816.321157,553149.842738,33402.847646,75594.692794,2201.427946,13648.996120,7582.712130
11,20180401,상계3.4동,950.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30461.0,6411.0,NaN,NaN,180.0,NaN,NaN,NaN,3450.0,5829.0,34698.0,7112.0,NaN,1352.72,895.26,...,1460.20,2312.26,3246.38,4130.65,4204.73,4770.53,5132.71,4789.20,4259.99,4047.90,3700.44,3595.17,3054.52,2728.23,2445.78,2187.87,1460.95,218434.000000,144050.000000,187218.000000,15809.000000,41863.000000,800.000000,6000.000000,12000.000000
12,20180401,상계5동,2220.0,1238.0,9373.0,NaN,NaN,NaN,NaN,NaN,26940.0,595.0,850.0,473.0,3064.0,NaN,NaN,219.0,1717.0,8401.0,42587.0,8456.0,153.0,875.51,569.93,...,724.82,1279.86,1698.98,2037.60,1807.80,2201.06,2082.55,2264.12,2377.15,2326.89,2379.57,2272.17,1856.77,1773.83,1691.27,1292.37,979.51,264724.126313,168104.680211,316868.551194,23005.810977,32962.415728,8265.203944,7145.603410,17233.608223
13,20180401,상계6.7동,5864.0,671.0,NaN,NaN,2148.0,3438.0,1512.0,NaN,80267.0,5827.0,NaN,4447.0,13980.0,58.0,NaN,267.0,41492.0,36750.0,164749.0,10522.0,NaN,3545.31,2665.24,...,3746.19,6671.93,8789.51,10992.63,9797.08,10845.05,12069.72,12000.17,11705.15,12308.42,11180.07,10975.39,9115.14,8293.46,6899.66,5180.43,3580.24,305230.555556,284482.111111,392026.111111,39181.000000,50646.222222,9884.777778,5706.888889,4588.333333
14,20180401,상계8동,984.0,NaN,876.0,NaN,NaN,NaN,NaN,NaN,49639.0,6097.0,NaN,NaN,166.0,NaN,NaN,NaN,NaN,4482.0,16150.0,3736.0,NaN,1053.23,782.66,...,1033.11,1679.12,2680.82,3083.06,2547.56,3269.14,3550.97,3661.61,3567.32,3661.34,3547.15,3309.40,2952.79,2707.20,2170.92,1744.76,1176.04,418510.000000,233016.000000,493280.000000,18548.000000,59270.000000,3364.000000,1937.000000,8093.000000
15,20180401,상계9동,202.0,498.0,NaN,NaN,NaN,NaN,NaN,NaN,70530.0,2162.0,NaN,NaN,1581.0,NaN,NaN,NaN,784.0,7053.0,22124.0,4197.0,NaN,718.41,512.44,...,593.62,1049.47,1387.99,1752.43,1543.95,2009.81,1978.00,2192.13,2233.82,2227.41,2218.99,2127.14,1854.97,1712.31,1445.87,1038.83,812.03,246251.907738,213292.586754,336993.540408,33085.320937,35396.653405,10712.329320,4302.998388,9652.663050
16,20180401,숭인1동,522.0,NaN,NaN,NaN,NaN,158.0,NaN,NaN,15566.0,659.0,NaN,NaN,NaN,NaN,NaN,NaN,254.0,1968.0,11806.0,758.0,151.0,401.32,271.45,...,482.30,847.31,1002.20,1278.32,1468.51,1636.09,1725.09,1614.52,1466.10,1480.79,1375.92,1313.75,1279.09,1169.23,1287.23,827.04,658.22,362924.675886,191542.092828,349976.669611,65779.531879,44199.521421,1682.000815,14535.007044,1063.500515
17,20180401,숭인2동,1563.0,NaN,NaN,48.0,NaN,NaN,NaN,241.0,31190.0,6607.0,NaN,105.0,294.0,NaN,NaN,44.0,430.0,5750.0,65393.0,4275.0,NaN,1075.26,769.93,...,1532.66,2649.14,3119.98,4023.85,4629.29,5251.35,5698.81,5072.53,4638.34,4303.41,4034.85,3726.27,3398.46,3416.98,2974.06,2334.10,1909.59,329643.302740,239674.199979,480578.399843,59897.549997,66735.771584,5351.221726,11363.221168,3977.332964
18,20180401,월계1동,5130.0,521.0,NaN,NaN,NaN,59624.0,NaN,NaN,50975.0,NaN,NaN,1352.0,2200.0,NaN,NaN,NaN,1379.0,11215.0,95364.0,7565.0,1301.0,1662.00,1089.11,...,1742.94,2607.92,3310.85,3957.42,4232.45,4534.62,4786.18,5023.99,5166.13,5433.79,5227.09,4741.15,4486.38,3998.56,3097.22,2424.56,1969.17,291283.147993,184315.578893,318549.373667,25045.336505,42804.338753,6803.111973,5999.778537,2730.333679
19,20180401,월계2동,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32860.0,NaN,NaN,193.0,234.0,318.0,NaN,NaN,43.0,2847.0,9606.0,2487.0,NaN,1326.73,930.07,...,1394.20,2174.25,2738.31,3204.99,2909.76,3565.50,3712.25,3937.27,4086.43,4112.27,4085.85,3809.83,3270.09,3051.35,2729.12,2243.72,1463.17,298691.536109,191695.887353,321787.946634,9760.804448,36421.616597,4221.601924,11130.405072,4088.201863
20,20180401,월계3동,756.0,NaN,NaN,NaN,NaN,NaN,588.0,NaN,574772.0,NaN,NaN,NaN,1705.0,NaN,NaN,6819.0,5185.0,9980.0,25804.0,6694.0,267.0,2242.36,1352.63,...,2296.22,3475.36,4613.28,5135.62,5917.30,6191.02,6712.45,6885.81,7057.92,7399.06,7351.06,6094.38,6155.49,5460.79,4838.47,3481.19,2281.40,275340.791277,320377.144993,425968.192780,20602.509324,48835.355435,1254.500568,3817.835061,8607.670562
21,20180401,이화동,876.0,3166.0,NaN,NaN,NaN,NaN,637.0,905.0,50134.0,16496.0,NaN,6289.0,7977.0,NaN,NaN,1025.0,148363.0,11095.0,255340.0,14954.0,NaN,741.76,557.45,...,1208.84,2173.47,3262.47,3670.68,4145.55,5206.50,6439.18,5436.04,5391.33,5274.24,4821.74,4351.45,3454.82,2973.60,2729.27,1719.86,1432.93,270003.962850,264599.130261,453789.604230,56053.992288,132792.648396,4818.166004,23715.830070,5557.665902
22,20180401,종로1.2.3.4가동,7025.0,30651.0,NaN,NaN,NaN,1528.0,981.0,3701.0,660591.0,91668.0,16808.0,158282.0,231073.0,66.0,NaN,5093.0,21423.0,35698.0,988541.0,21763.0,2451.0,4078.65,2902.11,...,7048.05,12956.02,18472.93,21255.50,25061.87,29138.59,31344.98,31372.50,28672.75,27002.54,25465.77,20202.88,16156.87,13840.05,11857.86,8825.83,4928.05,353259.831671,269654.859053,497193.679267,31279.673966,97998.231062,7120.997668,22483.150531,6611.576782
23,20180401,종로5.6가동,94.0,863.0,NaN,NaN,1881.0,NaN,NaN,NaN,12721.0,20433.0,7613.0,2599.0,283.0,NaN,NaN,176.0,45382.0,2304.0,194768.0,2327.0,NaN,1350.90,916.47,...,2186.04,3245.31,4802.88,5554.83,6428.63,7163.68,8282.85,7904.96,7076.94,7193.18,7011.83,5527.61,5437.12,4978.15,4222.90,3231.92,2077.32,196445.126600,171098.610265,308524.448830,16917.010902,35821.023085,7602.254899,14919.509615,24523.015804
24,20180401,중계1동,1068.0,385.0,NaN,NaN,NaN,NaN,NaN,23446.0,224037.0,1222.0,NaN,NaN,24046.0,NaN,NaN,NaN,5318.0,17246.0,59702.0,10270.0,2649.0,895.32,557.97,...,724.49,1770.36,2717.87,2789.54,2582.23,3617.62,3697.74,3441.42,3435.41,3271.09,3751.34,3265.91,2591.96,2420.40,2359.79,1427.90,1037.20,202858.684318,172568.194126,318444.146894,25367.241787,31002.989962,1472.749523,12204.496048,8207.497343
25,20180401,중계2.3동,NaN,12176.0,10407.0,NaN,NaN,24211.0,NaN,NaN,615961.0,7743.0,2778.0,3625.0,1449.0,176.0,NaN,1502.0,7369.0,20060.0,88005.0,11136.0,2951.0,1834.02,1142.21,...,2048.67,3583.48,4437.68,6139.19,5721.94,6802.14,7364.40,7772.14,6838.34,7601.24,6645.28,6251.16,5468.77,4759.57,4014.10,2806.47,1921.40,435471.069907,283808.115215,523396.643640,20387.593909,46679.186055,9272.597230,12054.196399,7881.597645
26,20180401,중계4동,816.0,942.0,NaN,NaN,NaN,NaN,NaN,2810.0,44214.0,297.0,NaN,88.0,1064.0,NaN,NaN,844.0,7211.0,9169.0,82305.0,6065.0,NaN,867.75,627.59,...,849.24,1463.52,2189.15,2402.35,2498.90,2859.38,2803.87,2745.56,2871.42,2902.00,2816.65,2762.73,2279.86,2083.92,1822.81,1338.06,929.42,201426.930732,262040.576555,409395.192548,42704.651981,41725.985651,3105.998932,3424.332156,5492.331445
27,20180401,중계본동,1043.0,206.0,270.0,NaN,NaN,19862.0,NaN,NaN,69307.0,1126.0,NaN,NaN,25953.0,NaN,NaN,NaN,1607.0,14215.0,88479.0,7263.0,308.0,805.00,471.27,...,596.40,1294.90,1772.13,2199.24,2169.69,2454.58,2447.54,2242.54,2298.45,2045.04,2342.82,2130.31,1565.38,1523.82,1598.35,1064.75,753.11,359607.901157,319937.245394,440386.878954,22156.993910,40373.322236,7181.664693,15451.329086,7629.664570
28,20180401,창신1동,1404.0,7723.0,NaN,NaN,NaN,NaN,66.0,NaN,16012.0,6043.0,197.0,2838.0,23214.0,4774.0,NaN,NaN,2965.0,6762.0,44536.0,5081.0,NaN,671.65,478.14,...,1039.23,1758.17,2305.02,2739.39,3466.89,3668.73,3932.94,3433.64,3315.14,3152.89,2810.69,2495.31,2567.40,2395.71,1913.95,1681.43,1728.37,305768.000000,190642.000000,328751.000000,9637.000000,32362.000000,18909.000000,24090.000000,910.000000
29,20180401,창신2동,14.0,37.0,NaN,NaN,93.0,NaN,NaN,NaN,10360.0,2897.0,NaN,167.0,NaN,44.0,NaN,NaN,1131.0,3971.0,32093.0,3143.0,NaN,178.24,154.70,...,274.73,429.47,606.83,696.35,798.25,870.48,881.58,892.19,886.11,848.87,811.73,746.06,718.81,727.88,545.09,506.99,323.93,533038.000000,220569.000000,351214.000000,26322.000000,57497.000000,37001.000000,29365.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13110,20190331,사직동,202.0,587.0,NaN,NaN,NaN,1941.0,1927.0,NaN,102663.0,2602.0,NaN,445.0,2357.0,50.0,NaN,14481.0,1550.0,17358.0,296783.0,7642.0,36.0,1250.33,946.99,...,4053.09,7360.95,8570.68,9712.87,9384.67,10989.35,11946.49,10273.34,9799.46,9697.21,8887.42,6720.92,5607.87,4686.45,4062.30,2762.14,1467.41,302127.683917,316582.430755,345317.174470,56351.987674,100761.727961,4831.748943,9135.998002,7875.248277
13111,20190331,삼청동,NaN,4999.0,NaN,NaN,NaN,NaN,2588.0,NaN,9289.0,19501.0,NaN,5004.0,454.0,NaN,NaN,909.0,678.0,4860.0,111209.0,4190.0,NaN,167.05,104.42,...,595.73,1327.75,1900.46,2373.02,2642.21,2883.03,3017.38,2844.33,2758.22,2456.42,1922.99,1405.02,1119.56,860.59,641.97,383.46,184.51,180449.500000,147724.500000,229251.000000,65660.500000,71363.000000,20409.000000,23954.000000,2273.500000
13112,20190331,상계10동,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11488.0,3122.0,NaN,999.0,6243.0,NaN,NaN,NaN,NaN,3853.0,10007.0,2480.0,NaN,733.73,526.83,...,834.74,1467.93,1945.16,2495.98,2155.46,2518.19,2803.63,3012.71,2856.57,2868.74,2864.60,2596.64,2084.33,1965.24,1585.42,1062.13,696.01,235429.000000,172510.666667,260620.333333,23761.000000,39335.000000,3212.000000,5160.666667,3061.333333
13113,20190331,상계1동,7986.0,2190.0,NaN,NaN,61.0,60807.0,182.0,40210.0,145425.0,5662.0,1135.0,1567.0,2156.0,20.0,NaN,1112.0,17839.0,24994.0,245911.0,15788.0,68.0,1861.36,1341.13,...,2737.14,4893.55,7687.55,8984.38,8148.35,8643.23,9403.98,10097.92,10332.08,10128.65,9397.82,7754.60,6546.01,5438.82,4417.28,3154.75,1960.14,196238.363636,160942.363636,243236.818182,14315.545455,33367.909091,5767.818182,5404.818182,7169.363636
13114,20190331,상계2동,7834.0,17959.0,NaN,NaN,442.0,9652.0,491.0,15995.0,819869.0,23551.0,NaN,12396.0,4611.0,NaN,NaN,4318.0,25211.0,64548.0,413564.0,32146.0,976.0,1160.51,840.02,...,1636.47,3667.22,4313.62,5833.68,4939.51,5726.16,6142.27,6619.44,6222.32,6554.38,6531.79,6067.82,4507.08,3620.10,2999.15,2214.22,1237.41,385137.455066,279780.183164,408943.710015,31450.131538,68240.014186,12562.502612,13363.752778,3079.250640
13115,20190331,상계3.4동,893.0,87.0,NaN,NaN,NaN,NaN,NaN,45.0,28172.0,1973.0,518.0,NaN,NaN,NaN,NaN,NaN,2255.0,9173.0,39037.0,4152.0,227.0,930.96,666.83,...,1341.74,2394.46,3652.91,4451.70,4483.51,5014.12,4960.22,4816.05,4247.13,4149.44,3627.44,3307.08,2735.78,2414.89,2212.16,1568.01,1157.21,285402.500000,180618.000000,271710.500000,35543.000000,22995.000000,2591.000000,3182.000000,1591.000000
13116,20190331,상계5동,1559.0,936.0,NaN,NaN,NaN,NaN,NaN,NaN,25574.0,431.0,114.0,NaN,2700.0,NaN,NaN,182.0,2085.0,7105.0,50130.0,8531.0,289.0,690.41,456.03,...,713.01,1224.83,1682.48,1982.55,1739.89,2061.34,2231.56,2271.36,2377.58,2450.26,2452.76,2215.42,1856.28,1696.39,1405.58,1107.24,756.55,277131.333333,174355.500000,274343.833333,8869.000000,26086.166667,4806.166667,5333.333333,1874.666667
13117,20190331,상계6.7동,5893.0,791.0,NaN,NaN,278.0,1414.0,590.0,NaN,102067.0,6779.0,NaN,222.0,18000.0,NaN,NaN,57.0,54982.0,25357.0,159081.0,12299.0,NaN,2483.11,1759.62,...,4276.40,6653.67,8841.60,11001.64,10321.71,11253.41,12457.62,13378.90,12873.41,12771.18,12060.64,11034.83,9134.23,7752.02,6188.14,4058.13,2427.55,289512.562975,229631.917755,327697.993743,18028.326876,52933.425486,3924.109706,4383.442874,4573.220584
13118,20190331,상계8동,1099.0,NaN,1362.0,NaN,NaN,NaN,NaN,NaN,39596.0,2233.0,NaN,NaN,234.0,NaN,NaN,NaN,5617.0,4224.0,16638.0,3434.0,NaN,1193.05,831.35,...,1393.38,2138.79,2790.19,3570.26,3090.03,3558.55,3883.12,4225.29,4323.38,4019.23,4037.56,3775.56,3275.52,2991.94,2559.85,1843.21,1158.52,638150.000000,408828.000000,471364.000000,9048.000000,34972.000000,12000.000000,15180.000000,30637.000000
13119,20190331,상계9동,357.0,141.0,NaN,NaN,NaN,NaN,NaN,NaN,70277.0,141.0,NaN,NaN,1572.0,NaN,NaN,NaN,118.0,5319.0,17569.0,3849.0,37.0,553.45,410.72,...,576.62,1049.21,1227.83,1702.65,1397.68,1702.27,1830.91,1981.24,2019.75,2092.49,2100.43,1886.08,1689.87,1444.56,1212.94,887.96,584.42,309572.445316,199694.405569,319754.448999,20499.340749,33668.345512,14666.338639,22727.674888,910.000329
13120,20190331,숭인1동,474.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17673.0,NaN,NaN,NaN,114.0,NaN,NaN,354.0,377.0,1848.0,14259.0,2951.0,132.0,249.82,205.26,...,544.78,818.02,1142.45,1396.99,1827.95,1808.70,1812.64,1726.44,1783.48,1418.92,1311.70,1183.00,1166.33,919.51,886.75,633.83,400.27,361214.675933,226050.110100,312813.152358,48627.523684,43592.521232,14182.006907,19863.509675,227.500111
13121,20190331,숭인2동,1444.0,772.0,NaN,2497.0,NaN,NaN,NaN,NaN,26390.0,6133.0,NaN,59.0,736.0,NaN,NaN,150.0,660.0,2291.0,63022.0,7966.0,NaN,954.71,710.78,...,2080.97,2952.59,4360.69,4908.13,6369.89,6104.60,6496.64,5780.80,6158.68,4954.65,4707.27,3707.38,3637.36,2898.94,2806.80,2058.77,1368.08,354474.163664,198240.335604,409999.773637,49909.408964,76700.513776,4445.500798,17365.103119,2441.200438
13122,20190331,월계1동,7867.0,461.0,NaN,NaN,NaN,74177.0,182.0,NaN,51552.0,545.0,NaN,NaN,1483.0,NaN,NaN,572.0,2818.0,11306.0,101856.0,10140.0,821.0,1135.84,711.28,...,1735.01,2155.83,3200.36,3669.45,3639.21,3868.70,4280.16,4341.40,4744.66,5095.05,4846.91,4255.79,4057.81,3405.10,3089.23,2284.40,1117.32,263983.528873,158952.857172,255129.131259,18949.094894,36189.690249,3029.899184,5236.198589,818.599779
13123,20190331,월계2동,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30346.0,NaN,NaN,521.0,252.0,45.0,NaN,13983.0,403.0,1239.0,10610.0,3995.0,NaN,985.94,703.98,...,1311.49,1872.11,2418.27,2529.28,2518.98,3024.13,3362.38,3473.16,3613.95,3457.77,3289.34,3126.77,2937.91,2496.38,2213.27,1514.51,1026.13,300753.000000,164964.200000,279035.400000,17336.000000,29397.400000,3945.600000,2263.400000,3228.000000
13124,20190331,월계3동,863.0,NaN,NaN,NaN,NaN,NaN,1629.0,NaN,856951.0,NaN,NaN,NaN,677.0,NaN,NaN,1672.0,5515.0,9872.0,19821.0,6896.0,572.0,1989.15,1255.49,...,2544.22,3597.22,5536.02,6208.38,5968.42,6750.87,8160.42,8104.82,7702.23,7714.76,7562.50,7046.22,6255.28,5339.91,4963.82,3686.57,1778.10,246418.241394,226920.915335,341737.539163,22240.491702,41582.317819,5447.664634,6529.830897,2527.999057
13125,20190331,이화동,679.0,5152.0,NaN,NaN,NaN,NaN,682.0,5892.0,54041.0,14515.0,NaN,6134.0,9582.0,NaN,NaN,1164.0,120533.0,12749.0,239341.0,17292.0,NaN,636.82,456.28,...,1664.31,2875.61,3431.96,4432.70,5351.70,5911.22,7095.91,6354.34,5987.29,6061.48,5501.71,4693.15,3687.35,3311.51,2851.43,1802.72,1144.47,408262.925880,341869.652219,573474.038743,49539.276720,144367.973790,9376.426869,27702.423542,19153.282237
13126,20190331,종로1.2.3.4가동,7879.0,18396.0,NaN,990.0,1317.0,4479.0,1339.0,1457.0,520668.0,54843.0,15994.0,170461.0,827558.0,NaN,NaN,5077.0,15746.0,28355.0,1050938.0,26782.0,1330.0,3549.30,2722.21,...,8626.29,16219.86,22678.99,24707.53,27668.66,32522.27,33167.82,31651.16,29754.73,29668.20,24893.98,19714.32,14584.81,12536.51,10313.97,8036.54,3965.25,368857.631386,233382.591875,389263.304004,30038.294475,85274.882013,6436.335210,28369.008274,1311.952764
13127,20190331,종로5.6가동,282.0,1584.0,NaN,NaN,1895.0,NaN,NaN,NaN,10744.0,17822.0,4995.0,2199.0,505.0,NaN,NaN,417.0,67653.0,1396.0,175413.0,1652.0,NaN,1243.71,904.97,...,2217.83,3849.03,6072.24,6332.82,7365.29,7784.11,8653.92,8297.39,7952.91,7844.85,7025.17,5350.83,4909.48,4264.39,3674.21,2457.07,1444.99,190947.824865,130869.801310,236113.842573,19199.507528,37155.264567,9204.503609,12431.504874,1718.750674

# Merge Data on GU

In [230]:
df_shinhan_total_GU.shape

(730, 23)

In [231]:
df_skt_time[skt_cols_list].shape

(13140, 26)

In [224]:
skt_cols_list = ['DATE', 'GU_NM', 'TMST_00', 'TMST_01', 'TMST_02', 'TMST_03',
                 "TMST_04", "TMST_05", "TMST_06", "TMST_07", "TMST_08", "TMST_09", "TMST_10",
                 "TMST_11", "TMST_12", "TMST_13", "TMST_14", "TMST_15", "TMST_16", "TMST_17", "TMST_18", "TMST_19",
                 "TMST_20", "TMST_21", "TMST_22", "TMST_23"]

In [225]:
df_gu_total = df_shinhan_total_GU.merge(df_skt_time[skt_cols_list], on=['DATE', 'GU_NM'])

In [221]:
gs_cols_list = ["DATE", "LCLS_10_P", "LCLS_20_P", "LCLS_30_P", "LCLS_40_P", "LCLS_50_P", "LCLS_60_P", 
                "LCLS_70_P", "LCLS_80_P", "GU_NM"]

In [222]:
df_gu_total = df_gu_total.merge(df_gs_total[gs_cols_list], on=['DATE', 'GU_NM'])

In [226]:
df_gu_total

,DATE,GU_NM,레저_USE_AMT,문화취미_USE_AMT,가구_USE_AMT,전기_USE_AMT,주방_USE_AMT,연료_USE_AMT,광학_USE_AMT,가전_USE_AMT,유통업_USE_AMT,의복_USE_AMT,직물_USE_AMT,신변잡화_USE_AMT,서적문구_USE_AMT,사무통신_USE_AMT,자동차판매_USE_AMT,자동차정비_USE_AMT,의료기관_USE_AMT,보건위생_USE_AMT,요식업소_USE_AMT,음료식품_USE_AMT,수리서비스_USE_AMT,TMST_00,TMST_01,TMST_02,TMST_03,TMST_04,TMST_05,TMST_06,TMST_07,TMST_08,TMST_09,TMST_10,TMST_11,TMST_12,TMST_13,TMST_14,TMST_15,TMST_16,TMST_17,TMST_18,TMST_19,TMST_20,TMST_21,TMST_22,TMST_23
0,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,1662.00,1089.11,854.97,594.57,650.91,1045.02,1419.65,1742.94,2607.92,3310.85,3957.42,4232.45,4534.62,4786.18,5023.99,5166.13,5433.79,5227.09,4741.15,4486.38,3998.56,3097.22,2424.56,1969.17
1,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,1326.73,930.07,592.66,510.69,535.75,804.79,1079.09,1394.20,2174.25,2738.31,3204.99,2909.76,3565.50,3712.25,3937.27,4086.43,4112.27,4085.85,3809.83,3270.09,3051.35,2729.12,2243.72,1463.17
2,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,2242.36,1352.63,1159.40,879.93,890.98,1396.69,1699.30,2296.22,3475.36,4613.28,5135.62,5917.30,6191.02,6712.45,6885.81,7057.92,7399.06,7351.06,6094.38,6155.49,5460.79,4838.47,3481.19,2281.40
3,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,4132.87,2917.44,2203.26,1817.76,1834.72,2327.95,3663.48,3864.96,5713.36,7013.81,8737.52,9302.84,9804.95,11344.93,11974.15,11899.08,12310.70,12736.98,11215.19,10853.89,9296.98,8484.84,6643.67,4320.01
4,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,3039.81,2170.86,1600.97,1360.46,1437.65,1756.39,2822.80,4504.96,5774.51,7616.00,9632.36,9509.23,11026.08,12229.50,11702.05,11217.02,11061.01,11367.48,9439.37,8870.76,7744.34,6746.97,5644.98,3777.58
5,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,1559.78,913.39,689.50,563.03,681.96,765.40,1227.37,1506.54,3792.38,3827.46,5258.56,4499.11,6433.77,6567.84,6775.92,6488.57,6623.68,6642.64,5733.46,4670.51,4207.90,3604.63,2345.26,1600.67
6,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,1395.21,833.90,640.82,530.24,534.51,740.10,1069.86,1344.72,2431.45,2974.89,3559.37,3453.80,4184.24,4649.12,4760.12,4692.49,4830.77,4971.98,4504.57,3746.18,3286.88,2856.21,2187.82,1375.13
7,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,805.00,471.27,303.95,249.77,271.16,314.91,413.89,596.40,1294.90,1772.13,2199.24,2169.69,2454.58,2447.54,2242.54,2298.45,2045.04,2342.82,2130.31,1565.38,1523.82,1598.35,1064.75,753.11
8,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,895.32,557.97,412.58,298.21,426.23,386.66,612.06,724.49,1770.36,2717.87,2789.54,2582.23,3617.62,3697.74,3441.42,3435.41,3271.09,3751.34,3265.91,2591.96,2420.40,2359.79,1427.90,1037.20
9,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,867.75,627.59,460.02,327.62,410.28,407.20,672.17,849.24,1463.52,2189.15,2402.35,2498.90,2859.38,2803.87,2745.56,2871.42,2902.00,2816.65,2762.73,2279.86,2083.92,1822.81,1338.06,929.42
10,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,1834.02,1142.21,676.55,600.46,754.38,977.30,1401.33,2048.67,3583.48,4437.68,6139.19,5721.94,6802.14,7364.40,7772.14,6838.34,7601.24,6645.28,6251.16,5468.77,4759.57,4014.10,2806.47,1921.40
11,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,2339.24,1699.94,1163.16,1095.40,1144.65,1524.08,2077.51,2728.90,4420.39,6444.59,8466.89,8467.84,9209.10,9498.13,9566.45,9946.06,9982.94,9091.23,8177.55,6591.49,5888.17,4784.02,3590.25,2433.04
12,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,1625.41,1323.89,888.53,729.69,923.67,897.11,1450.01,1502.95,3437.25,4815.83,6055.25,4921.98,6597.56,6901.16,7148.15,6654.20,7040.70,6470.97,6326.26,5096.45,4435.29,3627.67,3145.05,2008.57
13,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,1352.72,895.26,628.57,547.01,521.62,669.06,1097.15,1460.20,2312.26,3246.38,4130.65,4204.73,4770.53,5132.71,4789.20,4259.99,4047.90,3700.44,3595.17,3054.52,2728.23,2445.78,2187.87,1460.95
14,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,875.51,569.93,441.37,378.89,390.59,416.11,545.32,724.82,1279.86,1698.98,2037.60,1807.80,2201.06,2082.55,2264.12,2377.15,2326.89,2379.57,2272.17,1856.77,1773.83,1691.27,1292.37,979.51
15,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,3545.31,2665.24,1745.81,1625.37,1878.66,1991.53,2752.35,3746.19,6671.93,8789.51,10992.63,9797.08,10845.05,12069.72,12000.17,11705.15,12308.42,11180.07,10975.39,9115.14,8293.46,6899.66,5180.43,3580.24
16,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,1053.23,782.66,525.65,437.73,506.07,598.89,719.77,1033.11,1679.12,2680.82,3083.06,2547.56,3269.14,3550.97,3661.61,3567.32,3661.34,3547.15,3309.40,2952.79,2707.20,2170.92,1744.76,1176.04
17,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,718.41,512.44,319.44,283.92,325.17,360.93,472.51,593.62,1049.47,1387.99,1752.43,1543.95,2009.81,1978.00,2192.13,2233.82,2227.41,2218.99,2127.14,1854.97,1712.31,1445.87,1038.83,812.03
18,20180401,노원구,38739.0,40507.0,21890.0,NaN,2885.0,364300.0,13812.0,145154.0,3319741.0,111198.0,3804.0,29595.0,101676.0,842.0,NaN,24501.0,145702.0,281767.0,1834927.0,159470.0,10236.0,801.50,586.72,377.56,326.17,353.26,427.44,603.09,693.96,1360.05,1852.12,2198.11,1943.54,2561.30,2764.10,2628.86,2639.44,2673.32,2501.66,2478.50,2064.46,1882.61,1590.16,1295.66,823.39
19,20180401,종로구,18134.0,70755.0,NaN,48.0,1974.0,21652.0,6411.0,5655.0,1296166.0,221297.0,24618.0,204555.0,777664.0,5322.0,NaN,34222.0,360798.0,140561.0,2593107.0,108895.0,3457.0,609.11,447.82,301.75,217.03,237.07,318.75,519.28,1131.14,1588.58,1881.46,2520.06,2684.31,2721.33,3087.27,3097.34,2550.96,2464.35,2327.44,1933.71,1597.47,1331.83,1231.07,1041.82,624.62
20,20180401,종로구,18134.0,70755.0,NaN,48.0,1974.0,21652.0,6411.0,5655.0,1296166.0,221297.0,24618.0,204555.0,777664.0,5322.0,NaN,34222.0,360798.0,140561.0,2593107.0,108895.0,3457.0,1904.32,1319.04,951.80,779.08,779.14,1355.75,2473.61,3572.35,6145.07,7703.36,8742.41,9296.29,10060.52,10990.83,10166.17,9179.66,8899.18,8318.59,7009.69,5750.79,5137.36,4532.06,3589.93,2308.88
21,20180401,종로구,18134.0,70755.0,NaN,48.0,1974.0,21652.0,6411.0,5655.0,1296166.0,221297.0,24618.0,204555.0,777664.0,5322.0,NaN,34222.0,360798.0,140561.0,2593107.0,108895.0,3457.0,216.30,158.05,91.13,85.30,86.76,146.87,287.34,391.87,784.74,1437.12,1652.25,1985.75,2485.91,2640.20,2361.17,2126.52,1998.35,1794.76,1281.02,1059.50,875.79,691.84,433.89,229.83
22,20180401,종로구,18134.0,70755.0,NaN,48.0,1974.0,21652.0,6411.0,5655.0,1296166.0,221297.0,24618.0,204555.0,777664.0,5322.0,NaN,34222.0,360798.0,140561.0,2593107.0,108895.0,3457.0,1300.61,904.38,670.74,433.02,571.34,771.25,1031.59,1810.52,2557.06,3311.50,4508.32,4223.61,4491.89,5372.25,5155.72,4888.78,5111.07,5067.47,4148.24,3502.62,3217.30,2925.42,2374.94,1382.12
23,20180401,종로구,18134.0,70755.0,NaN,48.0,1974.0,21652.0,6411.0,5655.0,1296166.0,221297.0,24618.0,204555.0,777664.0,5322.0,NaN,34222.0,360798.0,140561.0,2593107.0,108895.0,3457.0,2523.88,2168.69,1672.82,1300.87,1400.14,1686.09,2277.03,3703.51,4682.92,7410.61,9315.43,10435.22,10004.64,11152.68,10460.65,9539.91,8973.38,7940.15,6992.54,6460.50,5661.25,5210.50,4416.75,3060.66
24,20180401,종로구,18134.0,70755.0,NaN,48.0,1974.0,21652.0,6411.0,5655.0,1296166.0,221297.0,24618.0,204555.0,777664.0,5322.0,NaN,34222.0,360798.0,140561.0,2593107.0,108895.0,3457.0,332.06,205.21,124.10,92.93,128.91,195.80,298.89,342.80,618.95,1197.67,1269.95,1006.10,1120.90,1243.10,1385.03,1311.60,1161.81,1207.60,1268.47,881.12,931.12,828.30,649.49,382.69
25,20180401,종로구,18134.0,70755.0,NaN,48.0,1974.0,21652.0,6411.0,5655.0,1296166.0,221297.0,24618.0,204555.0,777664.0,5322.0,NaN,34222.0,360798.0,140561.0,2593107.0,108895.0,3457.0,528.17,338.88,221.44,187.69,269.92,319.96,543.00,663.56,1140.63,1568.57,1905.76,1679.05,1982.61,2007.89,2036.69,1961.85,2013.86,2002.11,1590.22,1367.49,1335.09,1299.15,896.60,495.97
26,20180401,종로구,18134.0,70755.0,NaN,48.0,1974.0,21652.0,6411.0,5655.0,1296166.0,221297.0,24618.0,204555.0,777664.0,5322.0,NaN,34222.0,360798.0,140561.0,2593107.0,108895.0,3457.0,258.39,220.10,104.61,112.24,95.88,143.52,248.11,320.00,640.94,866.80,1092.78,1361.76,1585.97,1494.60,1603.95,1365.79,1297.30,1097.03,863.50,677.32,642.33,601.22,544.75,269.50
27,20180401,종로구,18134.0,70755.0,NaN,48.0,1974.0,21652.0,6411.0,5655.0,1296166.0,221297.0,24618.0,204555.0,777664.0,5322.0,NaN,34222.0,360798.0,140561.0,2593107.0,108895.0,3457.0,4078.65,2902.11,1919.04,1573.11,1548.67,3222.72,5771.73,7048.05,12956.02,18472.93,21255.50,25061.87,29138.59,31344.98,31372.50,28672.75,27002.54,25465.77,20202.88,16156.87,13840.05,11857.86,8825.83,4928.05
28,20180401,종로구,18134.0,70755.0,NaN,48.0,1974.0,21652.0,6411.0,5655.0,1296166.0,221297.0,24618.0,204555.0,777664.0,5322.0,NaN,34222.0,360798.0,140561.0,2593107.0,108895.0,3457.0,1350.90,916.47,639.29,477.45,556.56,1079.32,1684.49,2186.04,3245.31,4802.88,5554.83,6428.63,7163.68,8282.85,7904.96,7076.94,7193.18,7011.83,5527.61,5437.12,4978.15,4222.90,3231.92,2077.32
29,20180401,종로구,18134.0,70755.0,NaN,48.0,1974.0,21652.0,6411.0,5655.0,1296166.0,221297.0,24618.0,204555.0,777664.0,5322.0,NaN,34222.0,360798.0,140561.0,2593107.0,108895.0,3457.0,741.76,557.45,331.70,270.16,306.95,685.20,978.55,1208.84,2173.47,3262.47,3670.68,4145.55,5206.50,6439.18,5436.04,5391.33,5274.24,4821.74,4351.45,3454.82,2973.60,2729.27,1719.86,1432.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13110,20190331,노원구,47441.0,44255.0,33305.0,518.0,1248.0,382612.0,4032.0,140031.0,3668028.0,64150.0,4491.0,18220.0,87391.0,338.0,NaN,27887.0,209475.0,276906.0,1767927.0,187001.0,5649.0,1112.91,697.70,476.47,399.13,377.26,753.85,936.67,1375.86,2332.12,3053.03,3709.92,3357.33,4310.69,4985.27,4973.86,5006.64,4960.79,4876.50,4344.83,3419.95,3242.23,2869.25,1957.35,1001.04
13111,20190331,노원구,47441.0,44255.0,33305.0,518.0,1248.0,382612.0,4032.0,140031.0,3668028.0,64150.0,4491.0,18220.0,87391.0,338.0,NaN,27887.0,209475.0,276906.0,1767927.0,187001.0,5649.0,877.44,661.83,459.26,383.89,409.34,443.53,515.38,906.50,1966.04,2602.76,2848.19,2755.19,3249.85,3560.04,3217.08,3058.38,2968.17,3139.65,2514.82,2315.69,2061.24,2136.80,1395.54,970.69
13112,20190331,노원구,47441.0,44255.0,33305.0,518.0,1248.0,382612.0,4032.0,140031.0,3668028.0,64150.0,4491.0,18220.0,87391.0,338.0,NaN,27887.0,209475.0,276906.0,1767927.0,187001.0,5649.0,732.41,511.64,340.09,255.87,328.40,366.67,456.18,807.24,2066.37,2700.27,2478.69,2617.97,3428.08,3628.72,3335.49,3282.11,3398.43,3744.03,2967.49,2468.43,2057.69,2244.07,1218.74,808.24
13113,20190331,노원구,47441.0,44255.0,33305.0,518.0,1248.0,382612.0,4032.0,140031.0,3668028.0,64150.0,4491.0,18220.0,87391.0,338.0,NaN,27887.0,209475.0,276906.0,1767927.0,187001.0,5649.0,818.01,587.43,436.69,362.96,371.49,490.72,667.61,1047.38,1755.06,2500.48,2907.66,2760.58,3110.00,3396.73,3483.42,3332.55,3134.69,3108.58,2692.19,2316.44,1923.98,1713.70,1225.30,910.48
13114,20190331,노원구,47441.0,44255.0,33305.0,518.0,1248.0,382612.0,4032.0,140031.0,3668028.0,64150.0,4491.0,18220.0,87391.0,338.0,NaN,27887.0,209475.0,276906.0,1767927.0,187001.0,5649.0,1162.69,777.48,558.93,451.51,485.63,815.82,1158.07,1924.51,3178.68,4267.60,5484.73,5106.22,6031.62,6694.30,7006.69,6779.94,6704.16,6507.92,5782.63,4906.04,3937.01,3475.92,2482.07,1316.67
13115,20190331,노원구,47441.0,44255.0,33305.0,518.0,1248.0,382612.0,4032.0,140031.0,3668028.0,64150.0,4491.0,18220.0,87391.0,338.0,NaN,27887.0,209475.0,276906.0,1767927.0,187001.0,5649.0,1861.36,1341.13,973.93,895.83,898.78,1396.27,1857.53,2737.14,4893.55,7687.55,8984.38,8148.35,8643.23,9403.98,10097.92,10332.08,10128.65,9397.82,7754.60,6546.01,5438.82,4417.28,3154.75,1960.14
13116,20190331,노원구,47441.0,44255.0,33305.0,518.0,1248.0,382612.0,4032.0,140031.0,3668028.0,64150.0,4491.0,18220.0,87391.0,338.0,NaN,27887.0,209475.0,276906.0,1767927.0,187001.0,5649.0,1160.51,840.02,644.75,517.86,547.23,972.82,1204.12,1636.47,3667.22,4313.62,5833.68,4939.51,5726.16,6142.27,6619.44,6222.32,6554.38,6531.79,6067.82,4507.08,3620.10,2999.15,2214.22,1237.41
13117,20190331,노원구,47441.0,44255.0,33305.0,518.0,1248.0,382612.0,4032.0,140031.0,3668028.0,64150.0,4491.0,18220.0,87391.0,338.0,NaN,27887.0,209475.0,276906.0,1767927.0,187001.0,5649.0,930.96,666.83,532.94,432.18,444.59,680.77,925.17,1341.74,2394.46,3652.91,4451.70,4483.51,5014.12,4960.22,4816.05,4247.13,4149.44,3627.44,3307.08,2735.78,2414.89,2212.16,1568.01,1157.21
13118,20190331,노원구,47441.0,44255.0,33305.0,518.0,1248.0,382612.0,4032.0,140031.0,3668028.0,64150.0,4491.0,18220.0,87391.0,338.0,NaN,27887.0,209475.0,276906.0,1767927.0,187001.0,5649.0,690.41,456.03,322.68,288.46,272.10,415.21,464.60,713.01,1224.83,1682.48,1982.55,1739.89,2061.34,2231.56,2271.36,2377.58,2450.26,2452.76,2215.42,1856.28,1696.39,1405.58,1107.24,756.55
13119,20190331,노원구,47441.0,44255.0,33305.0,518.0,1248.0,382612.0,4032.0,140031.0,3668028.0,64150.0,4491.0,18220.0,87391.0,338.0,NaN,27887.0,209475.0,276906.0,1767927.0,187001.0,5649.0,2483.11,1759.62,1298.44,1086.91,1175.74,2041.97,2552.00,4276.40,6653.67,8841.60,11001.64,10321.71,11253.41,12457.62,13378.90,12873.41,12771.18,12060.64,11034.83,9134.23,7752.02,6188.14,4058.13,2427.55
13120,20190331,노원구,47441.0,44255.0,33305.0,518.0,1248.0,382612.0,4032.0,140031.0,3668028.0,64150.0,4491.0,18220.0,87391.0,338.0,NaN,27887.0,209475.0,276906.0,1767927.0,187001.0,5649.0,1193.05,831.35,691.90,567.14,598.06,771.48,1098.68,1393.38,2138.79,2790.19,3570.26,3090.03,3558.55,3883.12,4225.29,4323.38,4019.23,4037.56,3775.56,3275.52,2991.94,2559.85,1843.21,1158.52
13121,20190331,노원구,47441.0,44255.0,33305.0,518.0,1248.0,382612.0,4032.0,140031.0,3668028.0,64150.0,4491.0,18220.0,87391.0,338.0,NaN,27887.0,209475.0,276906.0,1767927.0,187001.0,5649.0,553.45,410.72,315.34,252.67,269.67,363.84,399.61,576.62,1049.21,1227.83,1702.65,1397.68,1702.27,1830.91,1981.24,2019.75,2092.49,2100.43,1886.08,1689.87,1444.56,1212.94,887.96,584.42
13122,20190331,노원구,47441.0,44255.0,33305.0,518.0,1248.0,382612.0,4032.0,140031.0,3668028.0,64150.0,4491.0,18220.0,87391.0,338.0,NaN,27887.0,209475.0,276906.0,1767927.0,187001.0,5649.0,733.73,526.83,392.00,317.84,309.35,454.17,548.68,834.74,1467.93,1945.16,2495.98,2155.46,2518.19,2803.63,3012.71,2856.57,2868.74,2864.60,2596.64,2084.33,1965.24,1585.42,1062.13,696.01
13123,20190331,종로구,20844.0,55675.0,NaN,3487.0,3212.0,27263.0,13623.0,7914.0,988158.0,138327.0,22396.0,219466.0,912117.0,4790.0,NaN,25952.0,365456.0,154745.0,2667436.0,131846.0,1575.0,529.98,413.88,271.47,245.44,287.11,347.99,773.47,1213.44,1877.54,2556.00,3451.88,3250.78,3848.60,4045.29,3857.42,3720.89,3442.19,2693.84,2198.02,1778.82,1492.35,1391.26,986.95,631.54
13124,20190331,종로구,20844.0,55675.0,NaN,3487.0,3212.0,27263.0,13623.0,7914.0,988158.0,138327.0,22396.0,219466.0,912117.0,4790.0,NaN,25952.0,365456.0,154745.0,2667436.0,131846.0,1575.0,1250.33,946.99,702.65,563.19,839.14,1929.22,5823.07,4053.09,7360.95,8570.68,9712.87,9384.67,10989.35,11946.49,10273.34,9799.46,9697.21,8887.42,6720.92,5607.87,4686.45,4062.30,2762.14,1467.41
13125,20190331,종로구,20844.0,55675.0,NaN,3487.0,3212.0,27263.0,13623.0,7914.0,988158.0,138327.0,22396.0,219466.0,912117.0,4790.0,NaN,25952.0,365456.0,154745.0,2667436.0,131846.0,1575.0,167.05,104.42,80.92,67.11,86.83,172.98,397.25,595.73,1327.75,1900.46,2373.02,2642.21,2883.03,3017.38,2844.33,2758.22,2456.42,1922.99,1405.02,1119.56,860.59,641.97,383.46,184.51
13126,20190331,종로구,20844.0,55675.0,NaN,3487.0,3212.0,27263.0,13623.0,7914.0,988158.0,138327.0,22396.0,219466.0,912117.0,4790.0,NaN,25952.0,365456.0,154745.0,2667436.0,131846.0,1575.0,867.03,579.76,379.13,321.18,388.19,697.86,953.80,1448.90,2323.34,3316.43,3873.55,3968.51,4645.73,4474.14,5022.17,5241.12,4927.44,4524.86,3743.74,3043.68,2876.13,2600.08,1650.92,840.19
13127,20190331,종로구,20844.0,55675.0,NaN,3487.0,3212.0,27263.0,13623.0,7914.0,988158.0,138327.0,22396.0,219466.0,912117.0,4790.0,NaN,25952.0,365456.0,154745.0,2667436.0,131846.0,1575.0,2365.90,1730.40,1321.27,1159.37,1206.50,1752.85,2433.28,3606.17,5668.56,8565.89,9855.41,10805.78,10692.20,10890.00,10775.08,11560.27,9724.58,8879.77,7582.04,6551.50,6233.87,5802.55,4041.20,2477.78
13128,20190331,종로구,20844.0,55675.0,NaN,3487.0,3212.0,27263.0,13623.0,7914.0,988158.0,138327.0,22396.0,219466.0,912117.0,4790.0,NaN,25952.0,365456.0,154745.0,2667436.0,131846.0,1575.0,274.31,205.10,144.95,75.22,162.00,329.93,297.48,483.11,914.23,1451.35,1524.70,1381.99,1641.30,1763.74,1739.17,1630.30,1441.43,1204.34,1239.36,1006.70,1033.26,760.43,559.63,415.73
13129,20190331,종로구,20844.0,55675.0,NaN,3487.0,3212.0,27263.0,13623.0,7914.0,988158.0,138327.0,22396.0,219466.0,912117.0,4790.0,NaN,25952.0,365456.0,154745.0,2667436.0,131846.0,1575.0,458.12,282.77,207.42,155.40,262.14,367.67,637.10,763.88,1706.79,1822.44,1837.93,1854.67,2073.84,2224.04,2253.68,2135.79,2117.08,1851.57,1653.76,1368.54,1257.85,1094.98,736.78,468.46
13130,20190331,종로구,20844.0,55675.0,NaN,3487.0,3212.0,27263.0,13623.0,7914.0,988158.0,138327.0,22396.0,219466.0,912117.0,4790.0,NaN,25952.0,365456.0,154745.0,2667436.0,131846.0,1575.0,191.03,157.18,111.59,94.06,95.62,158.76,272.26,392.67,969.99,1185.64,1479.13,1639.77,1722.42,1831.60,1787.39,1590.06,1337.85,1135.65,923.61,679.63,586.15,604.25,434.07,202.12
13131,20190331,종로구,20844.0,55675.0,NaN,3487.0,3212.0,27263.0,13623.0,7914.0,988158.0,138327.0,22396.0,219466.0,912117.0,4790.0,NaN,25952.0,365456.0,154745.0,2667436.0,131846.0,1575.0,3549.30,2722.21,2048.55,1607.81,1930.54,4533.05,9670.09,8626.29,16219.86,22678.99,24707.53,27668.66,32522.27,33167.82,31651.16,29754.73,29668.20,24893.98,19714.32,14584.81,12536.51,10313.97,8036.54,3965.25